apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}
  namespace: {ns}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {name}
  template:
    metadata:
      labels:
        app: {name}
    spec:
      containers:
      - name: {name}
        image: r.lvk.sh/{img}:{tag}
        ports:
        - containerPort: 1234
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred2