on:
  push:
    branches: [master]
    paths: 
      - 'packages/cloud/**'
jobs:
  build:
    name: Deploy Backend
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout Master

    - name: Prepare Yarn
      uses: lucemans/actions-yarn@v2.0.0

    - name: Login Docker
      run: echo ${{ secrets.DOCKER_LOGIN }} | docker login -u robot\$github --password-stdin r.lvk.sh
      
    - name: CHMOD
      run: sh -c "sudo chmod -R 777 $GITHUB_WORKSPACE" 

    - name: Install Dependencies
      run: yarn install
    - name: Build Image
      run: yarn build:backend
    - name: Push Image
      run: yarn push:backend
