on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout Master

    - name: Prepare Yarn
      uses: lucemans/actions-yarn@v2.0.0

    - name: Login Docker
      run: echo ${{ secrets.DOCKER_LOGIN }} | docker login -u robot\$github --password-stdin r.lvk.sh
      
    - name: CHMOD
      run: sh -c "sudo chmod -R 777 /github" 

#     - name: Install Docker
#       run: apk add --no-cache ca-certificates curl openssl git openssh-client docker

    - name: Install Dependencies
      run: yarn install
    - name: Build Image
      run: yarn build
